import type { Terminal, TUI } from "@earendil-works/pi-tui";

const SYNC_END = "\x1b[?2026l";
type Renderer = TUI & { doRender(): void };
type Visibility = "hidden" | "visible" | undefined;

/** Resolve Pi's stable forwarding reference without patching its proxy target. */
function resolveRenderer(tui: TUI): Renderer {
	const probe = Symbol("open-tui-renderer");
	const reference = tui as unknown as Record<symbol, () => Renderer>;
	if (!Reflect.set(reference, probe, function (this: Renderer) { return this; })) {
		throw new Error("TUI reference is not writable");
	}
	let renderer: Renderer | undefined;
	try {
		renderer = reference[probe]!();
		return renderer;
	} finally {
		Reflect.deleteProperty(renderer ?? reference, probe);
	}
}

/** Small reversible instance patch. Later wrappers retain an inert original on cleanup. */
function patch(target: object, key: string, value: unknown): () => void {
	const descriptor = Object.getOwnPropertyDescriptor(target, key);
	Object.defineProperty(target, key, {
		configurable: true, enumerable: descriptor?.enumerable ?? false, writable: true, value,
	});
	return () => {
		if (Reflect.get(target, key) !== value) return;
		if (descriptor) Object.defineProperty(target, key, descriptor);
		else Reflect.deleteProperty(target, key);
	};
}

/**
 * Bounded control scanner. CSI is carried across writes (at most 64 characters).
 * Terminal strings are streamed opaquely, including any apparent CSI in payloads.
 * Only ESC-form controls generated by the inspected Pi renderers are adapted.
 */
class CursorControls {
	private state: "text" | "escape" | "csi" | "long-csi" | "string" | "string-escape" = "text";
	private pending = "";
	private osc = false;
	visibility: Visibility;
	syncOpen = false;
	private syncStarted = false;

	private readonly regular: boolean;

	constructor(regular: boolean) {
		this.regular = regular;
	}

	write(data: string): string {
		const parts: string[] = [];
		let start = 0;
		for (let i = 0; i < data.length; i++) {
			const char = data[i]!;
			if (this.state === "text") {
				if (char !== "\x1b") continue;
				parts.push(data.slice(start, i));
				this.pending = char;
				this.state = "escape";
				start = i + 1;
			} else if (this.state === "escape") {
				this.pending += char;
				if (char === "[") this.state = "csi";
				else {
					parts.push(this.pending);
					this.pending = "";
					this.osc = char === "]";
					this.state = "]PX^_".includes(char) ? "string" : "text";
					if (char === "c" || char === "8") this.visibility = undefined;
				}
				start = i + 1;
			} else if (this.state === "csi") {
				this.pending += char;
				if (char >= "@" && char <= "~") {
					parts.push(this.control(this.pending));
					this.pending = "";
					this.state = "text";
				} else if (this.pending.length >= 64) {
					parts.push(this.pending);
					this.pending = "";
					this.visibility = undefined;
					this.state = "long-csi";
				}
				start = i + 1;
			} else if (this.state === "long-csi") {
				if (char >= "@" && char <= "~") this.state = "text";
			} else if (this.state === "string") {
				if (char === "\x1b") this.state = "string-escape";
				else if (this.osc && char === "\x07") this.state = "text";
			} else {
				if (char === "\\" || (this.osc && char === "\x07")) this.state = "text";
				else this.state = char === "\x1b" ? "string-escape" : "string";
			}
		}
		parts.push(data.slice(start));
		return parts.join("");
	}

	private control(sequence: string): string {
		if (sequence === "\x1b[?2026h") {
			this.syncOpen = true;
			this.syncStarted = true;
		} else if (sequence === SYNC_END) {
			if (this.regular && this.syncOpen) return "";
			this.syncOpen = false;
		} else if (sequence === "\x1b[?25h" || sequence === "\x1b[?25l") {
			const next = sequence.endsWith("h") ? "visible" : "hidden";
			if (this.visibility === next) return "";
			this.visibility = next;
		} else if (/^\x1b\[\?/.test(sequence) || sequence === "\x1b[u") {
			// Private mode changes/restores (including alternate screen) can invalidate visibility.
			this.visibility = undefined;
		}
		return sequence;
	}

	finish(failed: boolean): string {
		const pending = this.pending;
		this.pending = "";
		// Never insert sync-end into an incomplete CSI or an opaque terminal payload.
		if (this.state !== "text") this.visibility = undefined;
		const close = (this.syncOpen || (failed && this.syncStarted)) ? `${this.state !== "text" ? "\x18" : ""}${SYNC_END}` : "";
		this.syncOpen = false;
		this.state = "text";
		return pending + close;
	}
}

export interface CursorOutput {
	refresh(): void;
	cleanup(): void;
}

/** Non-public compatibility bridge; never patches host files, prototypes or stdout. */
export function installCursorOutput(tui: TUI, unavailable: () => void): CursorOutput | undefined {
	let renderer: Renderer;
	try {
		renderer = resolveRenderer(tui);
		if ((renderer.mode !== "regular" && renderer.mode !== "fullscreen") || ![renderer.doRender, renderer.requestRender, renderer.renderNow].every((method) => typeof method === "function") || renderer.doRender.constructor.name === "AsyncFunction") return undefined;
	} catch {
		return undefined;
	}
	const terminal: Terminal = renderer.terminal;
	if (![terminal?.write, terminal?.showCursor, terminal?.hideCursor, terminal?.start, terminal?.stop].every((method) => typeof method === "function")) return undefined;

	let active = true;
	let visibility: Visibility;
	let frame: CursorControls | undefined;
	const terminalUndo: Array<() => void> = [];
	let rendererUndo: Array<() => void> = [];
	const write = terminal.write;
	const show = terminal.showCursor;
	const hide = terminal.hideCursor;
	const undo = (entries: Array<() => void>) => { for (const restore of entries.reverse()) restore(); };

	function bind(next: Renderer): void {
		if (next.terminal !== terminal || ![next.doRender, next.requestRender, next.renderNow].every((method) => typeof method === "function") || next.doRender.constructor.name === "AsyncFunction"
			|| (next.mode !== "regular" && next.mode !== "fullscreen")) throw new Error("Unsupported TUI renderer");
		const entries: Array<() => void> = [];
		const render = next.doRender;
		try {
			entries.push(patch(next, "doRender", function (this: Renderer) {
				if (!active || frame) return render.call(this);
				const controls = new CursorControls(next.mode === "regular");
				controls.visibility = visibility;
				frame = controls;
				let completed = false;
				try {
					render.call(this);
					completed = true;
				} finally {
					try {
						const tail = controls.finish(!completed);
						if (tail) write.call(terminal, tail);
					} finally {
						visibility = completed ? controls.visibility : undefined;
						frame = undefined;
					}
				}
			}));
			for (const key of ["requestRender", "renderNow"] as const) {
				const method = next[key];
				entries.push(patch(next, key, function (this: Renderer, force?: boolean) {
					if (active && force) visibility = undefined;
					return method.call(this, force);
				}));
			}
		} catch (error) {
			undo(entries);
			throw error;
		}
		undo(rendererUndo);
		rendererUndo = entries;
		renderer = next;
		visibility = undefined;
	}

	const refresh = () => {
		if (!active || tui === renderer) return;
		try {
			const next = resolveRenderer(tui);
			if (next !== renderer) bind(next);
		} catch {
			cleanup();
			unavailable();
		}
	};
	const cleanup = () => {
		if (!active) return;
		active = false;
		visibility = undefined;
		undo(rendererUndo);
		undo(terminalUndo);
	};

	try {
		terminalUndo.push(patch(terminal, "write", function (this: Terminal, data: string) {
			if (!active) return write.call(this, data);
			if (!frame) {
				visibility = undefined;
				return write.call(this, data);
			}
			const filtered = frame.write(data);
			if (filtered) return write.call(this, filtered);
		}));
		for (const [key, method, next] of [["showCursor", show, "visible"], ["hideCursor", hide, "hidden"]] as const) {
			terminalUndo.push(patch(terminal, key, function (this: Terminal) {
				if (!active) return method.call(this);
				if (frame && frame.visibility === next) return;
				const result = method.call(this);
				// Some Terminal implementations use this.write(), others write stdout directly.
				if (frame) frame.visibility = next;
				else visibility = next;
				return result;
			}));
		}
		for (const key of ["start", "stop"] as const) {
			const method = terminal[key];
			terminalUndo.push(patch(terminal, key, function (this: Terminal, ...args: unknown[]) {
				if (active) {
					visibility = undefined;
					if (key === "start") refresh();
				}
				return Reflect.apply(method, this, args);
			}));
		}
		bind(renderer);
	} catch {
		cleanup();
		return undefined;
	}
	return { refresh, cleanup };
}
